# file: action.yml
# version: 1.1.0
# guid: 8c3e5f9a-7d4b-6e2a-1f8d-4c9e3a2b5d7f
---
name: "Auto Module Tagging"
description: >-
  Automatically tag Go modules based on commit messages
  and module paths
author: "jdfalk"
branding:
  icon: "tag"
  color: "blue"

inputs:
  github-token:
    description: "GitHub token for creating tags"
    required: true
  detect-modules:
    description: "Auto-detect changed Go modules"
    required: false
    default: "true"
  module-paths:
    description: "Explicit module paths (comma-separated)"
    required: false
    default: ""
  version-increment:
    description: "Version increment type (major, minor, patch)"
    required: false
    default: "patch"
  dry-run:
    description: "Perform dry run without creating tags"
    required: false
    default: "false"
  tag-prefix:
    description: "Prefix for module tags"
    required: false
    default: ""
  create-release:
    description: "Create GitHub release for each tag"
    required: false
    default: "false"
  commit-pattern:
    description: "Regex pattern to match commit messages for versioning"
    required: false
    default: ""

outputs:
  tags-created:
    description: "JSON array of tags that were created"
    value: ${{ steps.tag.outputs.tags }}
  modules-updated:
    description: "Number of modules updated"
    value: ${{ steps.tag.outputs.count }}

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23"

    - name: Detect changed modules
      id: detect
      if: inputs.detect-modules == 'true'
      run: |
        # Find all go.mod files
        MODULES=$(find . -name "go.mod" \
          -not -path "*/vendor/*" \
          -not -path "*/node_modules/*")

        # Get changed files in this commit
        CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD)

        # Find modules with changes
        CHANGED_MODULES=""
        while IFS= read -r mod; do
          MOD_DIR=$(dirname "$mod")
          if echo "$CHANGED_FILES" | grep -q "^$MOD_DIR/"; then
            if [ -z "$CHANGED_MODULES" ]; then
              CHANGED_MODULES="$MOD_DIR"
            else
              CHANGED_MODULES="$CHANGED_MODULES,$MOD_DIR"
            fi
          fi
        done <<< "$MODULES"

        echo "modules=$CHANGED_MODULES" >> $GITHUB_OUTPUT
        echo "Detected changed modules: $CHANGED_MODULES"
      shell: bash

    - name: Get latest tags for modules
      id: latest-tags
      run: |
        MODULES="${{ inputs.module-paths }}"
        if [ -z "$MODULES" ]; then
          MODULES="${{ steps.detect.outputs.modules }}"
        fi

        if [ -z "$MODULES" ]; then
          echo "No modules to process"
          exit 0
        fi

        IFS=',' read -ra MODULE_ARRAY <<< "$MODULES"

        for module in "${MODULE_ARRAY[@]}"; do
          # Get latest tag for this module
          if [ "$module" == "." ]; then
            LATEST_TAG=$(git describe --tags --abbrev=0 \
              --match "v*" 2>/dev/null || echo "v0.0.0")
          else
            LATEST_TAG=$(git describe --tags --abbrev=0 \
              --match "${module}/v*" 2>/dev/null || \
              echo "${module}/v0.0.0")
          fi
          echo "Module $module latest tag: $LATEST_TAG"
        done
      shell: bash

    - name: Create tags
      id: tag
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        MODULES="${{ inputs.module-paths }}"
        if [ -z "$MODULES" ]; then
          MODULES="${{ steps.detect.outputs.modules }}"
        fi

        if [ -z "$MODULES" ]; then
          echo "tags=[]" >> $GITHUB_OUTPUT
          echo "count=0" >> $GITHUB_OUTPUT
          exit 0
        fi

        IFS=',' read -ra MODULE_ARRAY <<< "$MODULES"
        TAGS_CREATED="[]"
        COUNT=0

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        for module in "${MODULE_ARRAY[@]}"; do
          # Get current version
          if [ "$module" == "." ]; then
            CURRENT_TAG=$(git describe --tags --abbrev=0 \
              --match "v*" 2>/dev/null || echo "v0.0.0")
            TAG_PREFIX=""
          else
            CURRENT_TAG=$(git describe --tags --abbrev=0 \
              --match "${module}/v*" 2>/dev/null || \
              echo "${module}/v0.0.0")
            TAG_PREFIX="${module}/"
          fi

          # Parse current version
          VERSION=${CURRENT_TAG#${TAG_PREFIX}v}
          IFS='.' read -ra VERSION_PARTS <<< "$VERSION"
          MAJOR=${VERSION_PARTS[0]:-0}
          MINOR=${VERSION_PARTS[1]:-0}
          PATCH=${VERSION_PARTS[2]:-0}

          # Increment version
          case "${{ inputs.version-increment }}" in
            major)
              MAJOR=$((MAJOR + 1))
              MINOR=0
              PATCH=0
              ;;
            minor)
              MINOR=$((MINOR + 1))
              PATCH=0
              ;;
            patch)
              PATCH=$((PATCH + 1))
              ;;
          esac

          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH}"
          NEW_TAG="${TAG_PREFIX}v${NEW_VERSION}"

          if [ "${{ inputs.dry-run }}" != "true" ]; then
            git tag -a "$NEW_TAG" -m "Auto-tagged $NEW_TAG"
            git push origin "$NEW_TAG"
            echo "Created tag: $NEW_TAG"
          else
            echo "Dry run: Would create tag $NEW_TAG"
          fi

          TAGS_CREATED=$(echo "$TAGS_CREATED" | \
            jq -c --arg tag "$NEW_TAG" '. + [$tag]')
          COUNT=$((COUNT + 1))
        done

        echo "tags=$TAGS_CREATED" >> $GITHUB_OUTPUT
        echo "count=$COUNT" >> $GITHUB_OUTPUT
      shell: bash

    - name: Output summary
      run: |
        echo "## Auto Module Tagging Summary" >> \
          $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Modules Updated:** \
          ${{ steps.tag.outputs.count }}" >> $GITHUB_STEP_SUMMARY
        echo "**Version Increment:** \
          ${{ inputs.version-increment }}" >> $GITHUB_STEP_SUMMARY
        echo "**Tags Created:** \
          ${{ steps.tag.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
        if [ "${{ inputs.dry-run }}" == "true" ]; then
          echo "**Status:** Dry run (no tags created)" >> \
            $GITHUB_STEP_SUMMARY
        fi
      shell: bash
